//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addition
    {
        public int Addition_ID { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public Nullable<decimal> Claim { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public int Salary_ID { get; set; }
    
        public virtual Salary Salary { get; set; }
    }
}
